"""Spec registry and traceability checks for the M10 spec-driven process.

One spec is one contract, one branch, one PR. A spec is *accepted* before code
exists, its acceptance criteria become tests before the implementation, and it
is not *verified* until those tests pass.

This module is the machine-readable half of that process: it parses spec
front-matter, renders the generated index, and provides the three traceability
rules the conformance tests assert.

    T1  every spec file carries complete, well-formed front-matter
    T2  every Accepted (or later) spec is named by at least one test
    T3  every transcript event kind emitted by the package is either
        grandfathered as pre-M10 or registered against the spec that
        introduced it

It lives inside the package rather than in a dev-tools directory because
S-001's third acceptance criterion anticipates the harness itself consuming a
spec as an instruction-ledger seed. Nothing here is imported by the agent loop,
it registers no tools, and it adds no runtime cost: ``harness/__init__.py`` is
empty, so importing the package does not import this module.
"""

from __future__ import annotations

import ast
import re
from dataclasses import dataclass
from pathlib import Path

#: Directory holding the specs, relative to the repository root.
SPECS_DIRNAME = "specs"

#: Generated index filename. Regenerated by ``python -m harness.specs``.
INDEX_FILENAME = "_index.md"

#: Files in ``specs/`` that are not specs.
NON_SPEC_FILES = frozenset({INDEX_FILENAME, "_template.md", "README.md"})

#: Required front-matter keys (T1). Order here is the order rendered.
REQUIRED_FIELDS: tuple[str, ...] = (
    "id",
    "title",
    "status",
    "lane",
    "depends",
    "effort",
)

#: Lifecycle states. ``Rejected`` and ``Superseded`` are terminal.
STATUSES = frozenset(
    {"Draft", "Accepted", "Implemented", "Verified", "Rejected", "Superseded"}
)

#: Statuses that oblige a spec to be named by a test (T2). A Draft has no
#: implementation yet, and a Rejected/Superseded spec is a record of a decision
#: not to build something -- requiring a test for either would be ceremony.
STATUSES_REQUIRING_TESTS = frozenset({"Accepted", "Implemented", "Verified"})

#: Lane A leaves every neutrality invariant intact and ships on unit tests.
#: Lane B deliberately changes the CODING path and owes a benchmark run.
LANES = frozenset({"A", "B"})

#: ``S-001``-style ids.
SPEC_ID_RE = re.compile(r"^S-\d{3}$")

#: A test claims a spec by naming its function ``def test_S001_...``. Matched
#: against a parsed function name, never against raw source: a spec id inside a
#: comment, docstring or string literal must not satisfy T2.
TEST_NAME_RE = re.compile(r"^test_(S\d{3})_")

#: Transcript event kinds that predate the spec process. New kinds must be
#: registered in :data:`EVENT_KIND_SPECS` instead of being added here; this set
#: is frozen history and should only ever shrink (if a kind is removed).
LEGACY_EVENT_KINDS = frozenset(
    {
        "agent_error",
        "compaction",
        "decision",
        "exec_capped",
        "grant",
        "landing_finish",
        "landing_turn",
        "message",
        "model_turn",
        "nudge",
        "run_error",
        "syntax_check",
        "tool_call",
        "tool_call_dropped",
        "tool_output_spilled",
        "tool_result",
        "truncation_continue",
        "truncation_continue_skipped",
        "verification_declared",
        "verification_failed",
        "verification_lint",
        "verification_passed",
        "wall_clock_stop",
        "wind_down",
    }
)

#: Event kinds introduced under the spec process, mapped to the spec that
#: introduced them (T3).
#:
#: The scan resolves the ``kind`` argument passed positionally or by keyword,
#: reached through an attribute or a bare name, as a literal or as a constant
#: imported from elsewhere in the package; anything it cannot resolve raises.
#: It matches ``append_event`` by *spelling*, so a call made through a
#: differently-named alias would still escape it -- catching that needs real
#: dataflow analysis. Nothing in the package does this, but the limit is real
#: and stated rather than implied.
#:
#: Scope note: T3 as stated in the plan is "every new event kind declares its
#: spec id in its payload". That is a property of a runtime payload and cannot
#: be asserted statically. What is enforced here is the checkable half -- every
#: emitted kind is accounted for by a spec -- so a new event cannot appear
#: without a spec owning it. The payload-level assertion belongs to whichever
#: spec first emits a new kind, where a real payload exists to assert against.
EVENT_KIND_SPECS: dict[str, str] = {
    "repo_checkpoint": "S-201",
    "repo_checkpoint_skipped": "S-201",
    "model_refusal": "S-110",
}


class SpecError(ValueError):
    """A spec file is missing, malformed, or violates a traceability rule."""


@dataclass(frozen=True)
class Spec:
    """One parsed spec, from its front-matter."""

    id: str
    title: str
    status: str
    lane: str
    depends: tuple[str, ...]
    effort: str
    path: Path

    @property
    def needs_test(self) -> bool:
        """Whether T2 obliges this spec to be named by a test."""
        return self.status in STATUSES_REQUIRING_TESTS


def _split_front_matter(text: str, path: Path) -> dict[str, str]:
    """Extract the leading ``---`` fenced key/value block.

    Deliberately a small hand-rolled parser rather than YAML: the schema is
    flat, fixed, and six keys wide, and a dependency-free parser cannot
    surprise us with type coercion (``status: Draft`` becoming a bool, an id
    like ``S-001`` parsing as something exotic).
    """
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise SpecError(f"{path}: missing opening '---' front-matter fence")
    try:
        end = next(i for i in range(1, len(lines)) if lines[i].strip() == "---")
    except StopIteration:
        raise SpecError(f"{path}: unterminated front-matter block") from None

    fields: dict[str, str] = {}
    for lineno, raw in enumerate(lines[1:end], start=2):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        key, sep, value = line.partition(":")
        if not sep:
            raise SpecError(f"{path}:{lineno}: expected 'key: value', got {raw!r}")
        key = key.strip()
        if key in fields:
            raise SpecError(f"{path}:{lineno}: duplicate front-matter key {key!r}")
        fields[key] = value.strip()
    return fields


def parse_spec(path: Path) -> Spec:
    """Parse one spec file, enforcing T1. Raises :class:`SpecError`."""
    fields = _split_front_matter(path.read_text(encoding="utf-8"), path)

    missing = [k for k in REQUIRED_FIELDS if k not in fields]
    if missing:
        raise SpecError(f"{path}: missing front-matter keys: {', '.join(missing)}")
    unknown = sorted(set(fields) - set(REQUIRED_FIELDS))
    if unknown:
        raise SpecError(f"{path}: unknown front-matter keys: {', '.join(unknown)}")

    spec_id = fields["id"]
    if not SPEC_ID_RE.match(spec_id):
        raise SpecError(f"{path}: id {spec_id!r} is not of the form 'S-001'")
    if fields["status"] not in STATUSES:
        raise SpecError(
            f"{path}: status {fields['status']!r} not one of "
            f"{', '.join(sorted(STATUSES))}"
        )
    if fields["lane"] not in LANES:
        raise SpecError(
            f"{path}: lane {fields['lane']!r} not one of {', '.join(sorted(LANES))}"
        )
    if not fields["title"]:
        raise SpecError(f"{path}: title must not be empty")
    if not fields["effort"]:
        raise SpecError(f"{path}: effort must not be empty")

    depends_raw = fields["depends"].strip()
    depends: tuple[str, ...] = ()
    if depends_raw and depends_raw != "-":
        depends = tuple(d.strip() for d in depends_raw.split(",") if d.strip())
        for dep in depends:
            if not SPEC_ID_RE.match(dep):
                raise SpecError(f"{path}: dependency {dep!r} is not a spec id")

    if not path.name.startswith(spec_id + "-"):
        raise SpecError(f"{path}: filename must start with its id {spec_id!r}")

    return Spec(
        id=spec_id,
        title=fields["title"],
        status=fields["status"],
        lane=fields["lane"],
        depends=depends,
        effort=fields["effort"],
        path=path,
    )


def load_specs(specs_dir: Path) -> list[Spec]:
    """Parse every spec in ``specs_dir``, sorted by id.

    Raises :class:`SpecError` on a duplicate id or a dependency naming a spec
    that does not exist -- a dangling dependency silently breaks the sequencing
    the plan relies on.
    """
    specs: list[Spec] = []
    for path in sorted(specs_dir.glob("*.md")):
        if path.name in NON_SPEC_FILES:
            continue
        specs.append(parse_spec(path))

    by_id: dict[str, Spec] = {}
    for spec in specs:
        if spec.id in by_id:
            raise SpecError(f"duplicate spec id {spec.id!r}: {by_id[spec.id].path}, {spec.path}")
        by_id[spec.id] = spec
    for spec in specs:
        for dep in spec.depends:
            if dep not in by_id:
                raise SpecError(f"{spec.path}: depends on unknown spec {dep!r}")
    _assert_acyclic(by_id)
    return sorted(specs, key=lambda s: s.id)


def _assert_acyclic(by_id: dict[str, Spec]) -> None:
    """Raise on a dependency cycle, self-dependency included.

    Dangling dependencies were already rejected; a cycle breaks the plan's
    sequencing identically and just as silently.
    """
    WHITE, GREY, BLACK = 0, 1, 2
    colour = dict.fromkeys(by_id, WHITE)

    def visit(node: str, trail: list[str]) -> None:
        colour[node] = GREY
        for dep in by_id[node].depends:
            if colour[dep] == GREY:
                cycle = " -> ".join([*trail, node, dep])
                raise SpecError(f"dependency cycle: {cycle}")
            if colour[dep] == WHITE:
                visit(dep, [*trail, node])
        colour[node] = BLACK

    for spec_id in sorted(by_id):
        if colour[spec_id] == WHITE:
            visit(spec_id, [])


def unnamed_specs(specs: list[Spec], named: set[str]) -> list[str]:
    """T2: ids at Accepted-or-later that no test names. Empty means compliant."""
    return sorted(s.id for s in specs if s.needs_test and s.id not in named)


def unowned_event_kinds(kinds: set[str]) -> list[str]:
    """T3: emitted kinds that are neither grandfathered nor spec-owned."""
    return sorted(kinds - LEGACY_EVENT_KINDS - set(EVENT_KIND_SPECS))


def stale_legacy_kinds(kinds: set[str]) -> list[str]:
    """Kinds frozen as legacy that the package no longer emits."""
    return sorted(LEGACY_EVENT_KINDS - kinds)


def unemitted_spec_kinds(kinds: set[str]) -> list[str]:
    """Kinds registered against a spec that nothing actually emits.

    The mirror of :func:`unowned_event_kinds`. Without it a spec could declare
    telemetry it never produces and T3 would stay green forever -- the same
    asymmetry that let a registered kind sit unemitted indefinitely.
    """
    return sorted(set(EVENT_KIND_SPECS) - kinds)


def render_index(specs: list[Spec]) -> str:
    """Render ``specs/_index.md``.

    Deterministic by construction: input is sorted by id and every cell is
    derived from front-matter, so regenerating without a spec change is a
    no-op diff.
    """
    lines = [
        "# Spec index",
        "",
        "<!-- GENERATED by `python -m harness.specs` - do not edit by hand. -->",
        "",
        "| id | title | status | lane | depends | effort |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for spec in specs:
        depends = ", ".join(spec.depends) if spec.depends else "-"
        lines.append(
            f"| [{spec.id}]({spec.path.name}) | {spec.title} | {spec.status} "
            f"| {spec.lane} | {depends} | {spec.effort} |"
        )
    lines.append("")
    return "\n".join(lines)


def _spec_id_from_test_name(name: str) -> str | None:
    """``test_S001_thing`` -> ``S-001``; anything else -> ``None``."""
    match = TEST_NAME_RE.match(name)
    if match is None:
        return None
    digits = match.group(1)[1:]
    return f"S-{digits}"


def spec_ids_named_by_tests(tests_dir: Path) -> set[str]:
    """Spec ids claimed by a test *function name* (T2).

    Parses rather than imports: a collection error in an unrelated test module
    must not silently empty this set and turn T2 green. Parses rather than
    text-scans: a spec id mentioned in a comment or docstring is not a test,
    and counting it would let a spec claim coverage it does not have.
    """
    named: set[str] = set()
    for path in sorted(tests_dir.rglob("test_*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                spec_id = _spec_id_from_test_name(node.name)
                if spec_id is not None:
                    named.add(spec_id)
    return named


def _string_constants(nodes: list[ast.stmt]) -> dict[str, str]:
    """Module-level ``NAME = "value"`` bindings, including annotated ones.

    The package declares its event-kind constants as ``X: Final[str] = "..."``,
    which the AST models as :class:`ast.AnnAssign`, not :class:`ast.Assign`.
    Handling only the latter silently failed to resolve exactly the constants
    this check exists to audit.
    """
    out: dict[str, str] = {}
    for node in nodes:
        if isinstance(node, ast.Assign) and isinstance(node.value, ast.Constant):
            if isinstance(node.value.value, str):
                for target in node.targets:
                    if isinstance(target, ast.Name):
                        out[target.id] = node.value.value
        elif isinstance(node, ast.AnnAssign) and isinstance(node.value, ast.Constant):
            if isinstance(node.value.value, str) and isinstance(node.target, ast.Name):
                out[node.target.id] = node.value.value
    return out


def event_kinds_in_source(package_dir: Path) -> set[str]:
    """Every transcript event kind emitted by the package (T3).

    Resolves both string literals and module-level string constants passed as
    the ``kind`` argument to ``append_event``. A kind that resolves to neither
    raises: an unresolvable kind means T3 cannot see it, and silently skipping
    it would make the check pass by not looking.
    """
    kinds: set[str] = set()
    for path in sorted(package_dir.rglob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        constants = _string_constants(tree.body)
        imports = _imported_names(tree)
        for node, bound in _calls_with_scope(tree):
            if not _is_append_event_call(node):
                continue
            kinds.add(
                _resolve_kind(node, path, package_dir, constants, imports, bound)
            )
    return kinds


def _is_append_event_call(node: ast.AST) -> bool:
    """Whether ``node`` calls ``append_event``, however it is spelled.

    Both ``store.append_event(...)`` and a bare ``append_event(...)`` count: a
    scan that only recognised attribute access would skip a call made through
    a local alias, and skipping is the failure mode T3 exists to prevent.
    """
    if not isinstance(node, ast.Call):
        return False
    if isinstance(node.func, ast.Attribute):
        return node.func.attr == "append_event"
    if isinstance(node.func, ast.Name):
        return node.func.id == "append_event"
    return False


def _resolve_kind(
    node: ast.Call,
    path: Path,
    package_dir: Path,
    constants: dict[str, str],
    imports: dict[str, tuple[str, str]],
    bound: frozenset[str] = frozenset(),
) -> str:
    """Extract the event kind from one ``append_event`` call, or raise.

    ``kind`` is the second positional parameter but nothing stops a caller
    passing it by keyword, and an earlier version of this scan read
    ``args[1]`` unconditionally -- so ``append_event(agent_id, kind="x", ...)``
    was skipped in silence and a new event kind could enter the package
    unaudited. Every shape must therefore either resolve or raise; there is no
    path that quietly returns nothing.
    """
    if any(isinstance(arg, ast.Starred) for arg in node.args):
        raise SpecError(
            f"{path}:{node.lineno}: append_event called with *args; T3 cannot "
            "determine the event kind"
        )

    kind_node: ast.expr | None = None
    if len(node.args) >= 2:
        # A positional kind cannot be overridden by **kwargs, so it wins
        # outright and no keyword scan is needed.
        kind_node = node.args[1]
    else:
        # Scan every keyword for `kind` first: rejecting on **kwargs mid-loop
        # made the outcome depend on argument order, so `append_event(a, **k,
        # kind="x")` raised while `append_event(a, kind="x", **k)` resolved.
        for keyword in node.keywords:
            if keyword.arg == "kind":
                kind_node = keyword.value
                break
        if kind_node is None and any(k.arg is None for k in node.keywords):
            raise SpecError(
                f"{path}:{node.lineno}: append_event called with **kwargs and no "
                "explicit kind; T3 cannot determine the event kind"
            )
    if kind_node is None:
        raise SpecError(
            f"{path}:{node.lineno}: append_event call has no resolvable 'kind' "
            "argument; T3 cannot audit it"
        )

    if isinstance(kind_node, ast.Constant) and isinstance(kind_node.value, str):
        return kind_node.value
    if isinstance(kind_node, ast.Name):
        if kind_node.id in bound:
            raise SpecError(
                f"{path}:{node.lineno}: event kind {kind_node.id!r} is a "
                "parameter of the enclosing function; T3 cannot audit it"
            )
        if kind_node.id in constants:
            return constants[kind_node.id]
        imported = _resolve_imported_constant(
            package_dir, kind_node.id, imports
        )
        if imported is not None:
            return imported
        raise SpecError(
            f"{path}:{node.lineno}: cannot resolve event kind from name "
            f"{kind_node.id!r}; T3 cannot audit it"
        )
    raise SpecError(
        f"{path}:{node.lineno}: event kind is a computed expression; "
        "T3 requires a literal or a module-level constant"
    )


def _imported_names(tree: ast.Module) -> dict[str, tuple[str, str]]:
    """Map each ``from X import Y [as Z]`` binding to ``(module, original)``.

    Only absolute intra-package imports are recorded; that is the form this
    package uses, and a relative import that is not understood simply fails to
    resolve, which raises loudly rather than resolving to something wrong.
    """
    out: dict[str, tuple[str, str]] = {}
    for node in tree.body:
        if isinstance(node, ast.ImportFrom) and node.module and node.level == 0:
            for alias in node.names:
                out[alias.asname or alias.name] = (node.module, alias.name)
    return out


def _calls_with_scope(
    tree: ast.Module,
) -> list[tuple[ast.Call, frozenset[str]]]:
    """Every Call paired with the parameter names of its enclosing functions.

    A name bound as a parameter shadows a module-level import, so resolving it
    through that import would produce a confidently wrong event kind. Knowing
    the enclosing scope lets the resolver raise instead.
    """
    found: list[tuple[ast.Call, frozenset[str]]] = []

    def walk(node: ast.AST, bound: frozenset[str]) -> None:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            args = node.args
            names = {a.arg for a in (*args.posonlyargs, *args.args, *args.kwonlyargs)}
            if args.vararg:
                names.add(args.vararg.arg)
            if args.kwarg:
                names.add(args.kwarg.arg)
            bound = bound | names
        if isinstance(node, ast.Call):
            found.append((node, bound))
        for child in ast.iter_child_nodes(node):
            walk(child, bound)

    walk(tree, frozenset())
    return found


def _resolve_imported_constant(
    package_dir: Path, name: str, imports: dict[str, tuple[str, str]]
) -> str | None:
    """Resolve ``name`` through the importing module's own import bindings.

    Scoped to what the module actually imported. A package-wide search by name
    would resolve a *local variable or parameter* that happens to share a name
    with some unrelated module-level constant, yielding a confidently wrong
    kind -- worse than failing, because the real kind then goes unaudited while
    a fabricated one enters the set.
    """
    binding = imports.get(name)
    if binding is None:
        return None
    module, original = binding
    parts = module.split(".")
    if parts and parts[0] == package_dir.name:
        parts = parts[1:]
    if not parts:
        return None
    candidate = package_dir.joinpath(*parts).with_suffix(".py")
    if not candidate.is_file():
        candidate = package_dir.joinpath(*parts, "__init__.py")
    if not candidate.is_file():
        return None
    tree = ast.parse(candidate.read_text(encoding="utf-8"), filename=str(candidate))
    return _string_constants(tree.body).get(original)


def main() -> None:
    """Regenerate ``specs/_index.md`` from front-matter."""
    root = Path(__file__).resolve().parent.parent
    write_index(root / SPECS_DIRNAME)


def write_index(specs_dir: Path) -> Path:
    """Regenerate the index in ``specs_dir`` and return its path.

    Refuses to write an empty index: ``load_specs`` legitimately returns ``[]``
    for a directory with no specs, and blindly rendering that would overwrite a
    real index with a bare header the next time this ran from the wrong place.
    """
    specs = load_specs(specs_dir)
    if not specs:
        raise SpecError(f"{specs_dir}: no specs found; refusing to write an empty index")
    index = specs_dir / INDEX_FILENAME
    index.write_text(render_index(specs), encoding="utf-8")
    print(f"wrote {index}")
    return index


if __name__ == "__main__":
    main()
